vlog -work work C:/Users/lehar/Documents/CEG3156 Lab/Lab2Sub/Lab2Processor8Bit/Lab2Processor8Bit/simulation/modelsim/Waveform7.vwf.vt
vsim -novopt -c -t 1ps -L cycloneive_ver -L altera_ver -L altera_mf_ver -L 220model_ver -L sgate work.ProcessorMIPSBenchTest_vlg_vec_tst
onerror {resume}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[31]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[30]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[29]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[28]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[27]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[26]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[25]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[24]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[23]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[22]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[21]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[20]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[19]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[18]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[17]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[16]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[15]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[14]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[13]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[12]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[11]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[10]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[9]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[8]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[7]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[6]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[5]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[4]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[3]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[2]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[1]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchAddressO[0]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[31]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[30]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[29]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[28]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[27]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[26]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[25]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[24]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[23]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[22]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[21]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[20]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[19]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[18]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[17]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[16]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[15]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[14]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[13]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[12]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[11]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[10]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[9]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[8]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[7]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[6]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[5]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[4]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[3]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[2]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[1]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchMuxO[0]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[31]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[30]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[29]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[28]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[27]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[26]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[25]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[24]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[23]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[22]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[21]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[20]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[19]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[18]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[17]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[16]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[15]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[14]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[13]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[12]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[11]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[10]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[9]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[8]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[7]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[6]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[5]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[4]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[3]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[2]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[1]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOffsetO[0]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/BranchOut}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/GClock}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/GResetBar}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[31]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[30]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[29]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[28]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[27]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[26]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[25]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[24]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[23]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[22]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[21]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[20]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[19]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[18]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[17]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[16]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[15]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[14]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[13]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[12]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[11]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[10]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[9]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[8]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[7]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[6]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[5]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[4]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[3]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[2]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[1]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/InstructionOut[0]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[31]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[30]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[29]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[28]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[27]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[26]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[25]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[24]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[23]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[22]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[21]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[20]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[19]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[18]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[17]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[16]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[15]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[14]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[13]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[12]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[11]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[10]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[9]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[8]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[7]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[6]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[5]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[4]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[3]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[2]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[1]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpAddressO[0]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/JumpO}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/MemWriteOut}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/MuxOut}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/MuxOut[7]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/MuxOut[6]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/MuxOut[5]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/MuxOut[4]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/MuxOut[3]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/MuxOut[2]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/MuxOut[1]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/MuxOut[0]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[31]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[30]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[29]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[28]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[27]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[26]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[25]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[24]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[23]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[22]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[21]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[20]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[19]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[18]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[17]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[16]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[15]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[14]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[13]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[12]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[11]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[10]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[9]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[8]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[7]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[6]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[5]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[4]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[3]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[2]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[1]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PC4AddedO[0]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[31]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[30]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[29]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[28]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[27]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[26]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[25]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[24]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[23]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[22]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[21]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[20]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[19]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[18]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[17]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[16]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[15]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[14]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[13]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[12]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[11]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[10]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[9]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[8]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[7]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[6]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[5]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[4]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[3]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[2]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[1]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCin[0]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[31]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[30]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[29]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[28]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[27]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[26]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[25]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[24]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[23]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[22]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[21]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[20]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[19]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[18]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[17]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[16]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[15]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[14]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[13]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[12]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[11]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[10]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[9]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[8]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[7]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[6]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[5]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[4]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[3]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[2]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[1]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/PCOut[0]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ReadReg1O}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ReadReg1O[4]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ReadReg1O[3]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ReadReg1O[2]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ReadReg1O[1]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ReadReg1O[0]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ReadReg2O}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ReadReg2O[4]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ReadReg2O[3]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ReadReg2O[2]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ReadReg2O[1]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ReadReg2O[0]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/RegWriteOut}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ValueSelect}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ValueSelect[2]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ValueSelect[1]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ValueSelect[0]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/WriteRegO}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/WriteRegO[4]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/WriteRegO[3]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/WriteRegO[2]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/WriteRegO[1]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/WriteRegO[0]}
add wave {ProcessorMIPSBenchTest_vlg_vec_tst/i1/ZeroOut}
run -all
